version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
    - dependency-name: "GraphQL"
    - dependency-name: "GraphQL.MicrosoftDI"
    - dependency-name: "GraphQL.SystemTextJson"
    - dependency-name: "GraphQL.Server.Transports.AspNetCore"
    - dependency-name: "GraphQL.Server.Ui.GraphiQL"
    - dependency-name: "GraphQL.Server.Ui.Playground"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
